### ISSUE TITLE
refactor nose tests to pytest style

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#199]
Saw this in the logs: `PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release`

**Comment by IAlibay** [comment]
This seems to all be network plotting related things. Are we still even supporting that code branch? (I thought it had broken some time ago)

**Comment by richardjgowers** [comment]
Yeah I think there might be some in gufe too, I think it's @dwhswenson 's preferred style

**Comment by dwhswenson** [comment]
So, my preferred style is to have bidirectional traceability between test and test object. That is, given the test name, I can tell you what unit it tests, and given the object to be tested, I can tell you what at least one test is named (and give the prefix for other test names). Importantly, all of this can be done without existing familiarity with the source. Example:

```python
# package/subpackage/module.py
class SomeClass:
    def some_method(self):
        ...
```
```python
# package/tests/subpackage/test_module.py
class TestSomeClass:
    def test_some_method(self):
        ...

    def test_some_method_special_case(self):
        ...
```

I would argue that this is a best practice when writing tests -- it makes it easier to check that you're testing everything, it makes it easier to find missing tests later, and it makes it easier to identify where the problem is in the code when a test fails. In particular, it makes it easier for new people to work with tests, since a the test suite structure mirrors the code structure.

Where `setup`/`teardown` come into play is that you frequently have a number of fixtures that are repeated for a given test class. Rather than filling up the test method arguments with the same fixtures for every test, you use `setup` / `teardown` for class-level fixtures, and access via `self.fixture`.

The actual change in pytest is that they're removing support for the names `setup` / `teardown` as an alternative for their preferred `setup_method` / `teardown_method` names. https://github.com/pytest-dev/pytest/pull/9907#issuecomment-1272546459 I find this a little annoying, since I thought that `setup` / `teardown` were the most commonly used names across xUnit testing frameworks. But this is just a matter of renaming (and me breaking habits that are about a decade old).

**Comment by richardjgowers** [comment]
@dwhswenson so agree with your bidirectionality thing

We could just rename the methods from their xUnit names (which I agree is odd) but there's also the issue that we have tests written in two different styles which is annoying for development.  I think moving forwards we should stick to pytest & fixtures rather than xUnit style.
