### ISSUE TITLE
User versioneer?

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#23]
It would be a lot easier to just let versions be handled automatically, how do we feel about setting up versioneer?

**Comment by dwhswenson** [comment]
Question on versioneer -- I disliked it when I looked into it a few years back, because (IIRC) there was something incorrect in how it handled non-release versions (note that this may have been an issue in how some repo I was looking at *used* versioneer, as opposed to a problem with the tool itself.)

Specifically, the problem I remember was with development versions. After you release `v1.0.0`, the code on `main` should be `v1.0.1.dev0` (which may bump to `v1.1.0.dev0` or even `v2.0.0.dev0` when a sufficient change has been included). You should never have a time where the code on `main` is ahead of a release while the version number is behind the release (which includes the fact that `v1.0.0.dev` is before `v1.0.0`).

I don't remember if this was something that was outside the scope of versioneer, or something that versioneer handled poorly, or just something that was handled poorly in the specific repos I looked at. In any case, I ended up writing [my own toolkit](https://github.com/dwhswenson/autorelease/) to ensure this behavior (and to automate cutting a release on GitHub/deploying to PyPI). I'm not saying that we should necessarily use that toolkit (some parts of the code are a little janky, to be honest), but I do want to be sure we have a solution to the problems that I solved there.

**Comment by IAlibay** [comment]
I _think_ `dev0` is support as part of some of the modified pep440 styles: https://github.com/python-versioneer/python-versioneer/blob/master/details.md It's not super clean though.

But yeah I'm not too fussed whichever way we go here, as long as we have a detailed workflow and can go `openfe.__version__`.

**Comment by dwhswenson** [comment]
So, here's my understanding from the Versioneer docs (and I'm pretty sure this is what I didn't like): Say we've released 1.0, and we've merged in some major feature that will be part of 1.1. What version does `main` represent at that point? To me, that's clearly the `1.1.0.dev0` : it's a development version of 1.1. Versioneer treats it as still part of 1.0.

If we go with Versioneer, I could probably live with the `pep440-post` style. It's at least technically correct that what I think of as `1.1.0.dev0` could also be (by ordering) `1.0.0.post25`, and it includes the commit hash. Some of the other styles don't respect PEP440 ordering, which I would find very annoying.

**Comment by mikemhenry** [comment]
Is there something other than Versioneer? I've been happy with it, we do want something that is automated.

**Comment by richardjgowers** [comment]
@mikemhenry do you want to go ahead with versioneer? it's probably the least bad of options

**Comment by dwhswenson** [comment]
Yeah, the thing I use is my own toolkit, [autorelease](https://github.com/dwhswenson/autorelease/). Its version management stuff requires that you not edit `setup.py` (everything must be in `setup.cfg`) and isn't as robust as Versioneer on edge cases. I think we will want to edit `setup.py` to error if non-pip-installable stuff is missing.

However, we might consider using the automated release-to-PyPI process in autorelease. That just involves a set of GitHub actions with hooks that you can customize with scripts. I've found it convenient as a way to make the release process as easy as merging a PR on GitHub.

If we use Versioneer: the `pep440-post` style, please. Some of the other styles are misleading in citing PEP440 -- any individual version string might match PEP440, but a group of them might not. PEP440 defines an ordering, not just a regex.

**Comment by mikemhenry** [comment]
I'm happy to setup either, on first pass `versioneer` is more simple, but [autorelease](https://github.com/dwhswenson/autorelease/) does have some nice features, such as the release-to-PyPI process, but as soon as we start having dependencies that don't live on PyPI and only on `conda-forge` I imagine releasing to PyPI will be less important.

**Comment by mikemhenry** [comment]
If there are no objections I will go ahead and add `versioneer` using the `pep440-post` style, we can talk about it in our meeting today as well

**Comment by richardjgowers** [comment]
Yep please

**Comment by dwhswenson** [comment]
Resolved by #45.
