### ISSUE TITLE
cli: version doesn't work on editable installs

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#490]
currently a developer install will give: `openfe --help` -> `AttributeError: module 'openfecli' has no attribute '__version__'`

**Comment by dwhswenson** [comment]
This is odd, since it is clearly defined in `__init__.py`:

https://github.com/OpenFreeEnergy/openfe/blob/304d85a82700ad8aa4ad36322d219d743ecd0d5d/openfecli/__init__.py#L7-L8

With the following install process, I do not reproduce:

```
$ mamba create -n test-openfe-dev-version python
$ mamba activate test-openfe-dev-version
$ mamba install --only-deps openfe
$ hash -r  # to ensure I have the right python
$ python -m pip install -e .  # from the openfe root directory 
$ which openfe
/Users/dwhs/mambaforge/envs/test-openfe-dev-version/bin/openfe
$ openfe --version
openfe, version 0.11.1+6.gfc2c61b.dirty
```

Can you check what happens if on `import openfe; openfe.__version__` and `import openfecli; openfecli.__version__`? Both of which should just call `importlib.metadata.version('openfe')`.

Note that, for dev installs, this should give whatever version you last did `python -m pip install -e .` with. Because of the tools we chose to use for versioning, dev install version will be inaccurate (one of the reasons I dislike most off-the-shelf versioning tools and wrote my own for my projects).

**Comment by richardjgowers** [comment]
@dwhswenson hmm I think it's just my `-e` installs aren't working at all. My `import openfe; dir(openfe)` gives only the basic items and nothing specific.  I think this is because I was overwriting a conda installed openfe rather than creating the `--only-deps` environment as above, this seems to work for develop installs
