### ISSUE TITLE
Generate network from indices will create non connected graphs if passed extra ligands

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#510]
In hindsight this makes sense, but it's definitely not a behaviour that users will be expecting.

I would expect folks to at least get a warning about this? Probably even an error.

**Comment by IAlibay** [comment]
Personally I think that if you're passing in a list of edges to a method that is meant to then turn them into a network, you probably should say "hey buddy, you sure about this?".

I.e. the expectation is that this method takes in some kind of pre-defined network, I'd probably even expect to have a way to represent disconnected nodes in the list?

**Comment by dwhswenson** [comment]
I think a warning is reasonable here; probably not an error (since something that takes us from `LigandNetwork` to `AlchemicalNetwork` can recover at that point.) That said, we error on MST if a node is disconnected (IMO, that one should probably error by default, but maybe give an option to quiet that into a warning. Same might be work here.)

**Comment by richardjgowers** [comment]
probably a warning, I made the connected check here: https://github.com/OpenFreeEnergy/gufe/pull/214 then adding the warning into these generator methods is trivial
