### ISSUE TITLE
Review settings names

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#665]
We should review our settings name & change things ahead of the 1.0 release.

**Comment by hannahbaumann** [comment]
From discussion from this weeks power hour:

- AlchemicalSamplerSettings:
1. Potentially make 3 subclasses for different samplers.
2. If not 1.: Potentially rename `flatness_criteria` to `sams_flatness_criteria` and `gamma0` to `sams_gamma0`
3. rename 
`online_analysis_interval` to `real_time_analysis_interval`, 
`online_analysis_minimum_iterations` to `real_time_analysis_minimum_iterations`, 
`online_analysis_target_error` to `real_time_analysis_target_error`
4. Change doc string of `online_analysis_target_error` to make it clear how the error is calculated and that the ERROR has to be below this value, not the free energy as currently stated
5. Potentially move `n_repeats` to SimulationSettings or upstream
6. Potentially combine AlchemicalSamplerSettings with SimulationSettings.

**Comment by hannahbaumann** [comment]
- AlchemicalSettings:
1. remove `flatten_torsions`
2. rename `interpolate_old_and_new_14s`
3. change doc string for `interpolate_old_and_new_14s`
4. Move `lambda_functions` and `lambda_windows` to different `LambdaSettings` class.
5. rename `softcore_LJ_v2` to `softcore_LJ` and unse literal `'gapsys'` instead of `True`/`False`
6. rename `unsampled_endstates` (ideas: `sample_non_alchemical_endstates` `True/False`, or `endstate_correction` )and rewrite the doc string to make it clear what the setting does
7. Move `use_dispersion_correction` to where PME stuff is (or `ForceFieldSettings`?)

**Comment by hannahbaumann** [comment]
- IntegratorSettings:
1. rename `n_steps`
2. Move `n_steps` to (?) `AlchemicalSamplerSettings`?

**Comment by hannahbaumann** [comment]
- SimulationSettings:
1. Potentially combine `SimulationSettings`  and `AlchemicalSamplerSettings`
2. Potentially move settings that are only related to outputs (e.g. `output_filename`) to an `OutputSettings` or similar.

**Comment by hannahbaumann** [comment]
- SystemSettings:
1. Merge `SytemSettings` to `ForceFieldSettings`
2. Rename `nonbonded_method`, maybe two separate entries for LJ and Coulomb
