### ISSUE TITLE
Using other versions of small ligand ff (GAFF) instead of the default one

### ISSUE THREAD

**Issue by palominohernandez** [OpenFreeEnergy/openfe#870]
Hi all,

I tried changing to different gaff versions. Just for starters, I hardcoded one.

```
rbfe_settings.forcefield_settings.small_molecule_forcefield='gaff-2.11'

```

There was no issue to write the transformations to disk, but when running them, I got the following error:

```
Error: The protocol unit 'LIG1 to LIG2 repeat 0 generation 0' failed with the error message:
GAFFNotSupportedError: This release (0.13.x) of openmmforcefields temporarily drops GAFF support and thereby the GAFFTemplateGenerator class. Support will be re-introduced in future releases (0.14.x). To use this class, install version 0.12.0 or older.
```

I just wanted to report this point: should there be a fail-check mechanism from the generation of the json files?

**Comment by IAlibay** [comment]
Thanks for opening this @palominohernandez 

GAFF support was temporarily removed in openmmforcefields 0.13.0 due to some issues with ambertools, as far as we know the developers are looking into ways to re-enable it, see https://github.com/openmm/openmmforcefields/pull/334 for example.

Doing a check at Protocol generation is a possibility, although we will need to give it a little bit more thought.

Some initial thoughts on why this might be a little bit complicated:
1. We can't guarantee that the environment at run time will be the same as setup time, so if you verify any xml / ffxml paths, you might find yourself in cases where you have either false negatives or false negatives
2. Similarly any file paths you pass might not reflect where you build at setup time.

That being said, throwing a warning wouldn't cost much either.

**Comment by jameseastwood** [comment]
This issue has been fixed in up-to-date version of openmmforcefields. Feel free to re-open the issue if it isn't resolved for you.
