### ISSUE TITLE
Molecular box auto padding

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/openfe#96]
There should probably be a way (i.e. classmethod) to auto generate a box size for a given protein (or largest thing), this description is good for how this should behave: 

https://github.com/choderalab/perses/issues/949#issuecomment-1057581435

**Comment by dwhswenson** [comment]
I'm not sure what the new implementation in OpenMM is, but a while ago, I wrote something that found the largest distance between protein atoms (using the convex hull to make it reasonably fast) and then added some padding to that. There's probably a more rigorous approach, but the code for that can be found in these (might be useful when we come to this issue):

* https://github.com/dwhswenson/prepomm/blob/master/prepomm/box_vectors.py
* https://github.com/dwhswenson/prepomm/blob/master/prepomm/analysis.py

**Comment by IAlibay** [comment]
I'm not sure I follow the idea here, is this to create the box size before we create the OpenMM System? Modeller in OpenMM can just create a padded box otherwise.

**Comment by IAlibay** [comment]
So couple of early thoughts here - depending on whether or not you want to make this optional or mandatory, you're possibly opening a can of worms here with the latter.

There are many cases (say simulations where you attempt to derive a direct measure of enthalpy) where you might not want to a priori define a box, but instead derive your box from a connecting box along an edge (i.e. it'll be method generated rather than something you want to do beforehand, especially since a dH calculation essentially has the same thermodynamic state definition as half a dG calculation). Similarly, an RBFE will be defined based on the box of the lambda 0 state, etc...

Ignoring this, if you want to define an a priori box definition you should also consider if we want to block folks off on a given correction method / MD engine this early on in our definition.

Examples:
1. Rocklin corrections are only derived for cubic boxes currently
2. Dodecahedrons are not supported in AMBER
3. Membranes are weird.

**Comment by IAlibay** [comment]
That being said, I am not against standardising the generation of boxes - indeed the addition of ions is vastly inconsistent being MD engines, which led me to put together this (feature completely but unfinished in docs etc..) little thing: https://github.com/IAlibay/saltpy

**Comment by richardjgowers** [comment]
@IAlibay ok interesting, so maybe we can't always numerically define the system cell, if that is the case I'd still rather we declare the box as stemming from a particular method... `system = (Protein(), Ligand(), Solvent(), RocklinMethod.GenBox())` rather than this happening implicitly.  I'm also OK with a microstate being incompatible (e.g. because it's a dodecahedron) with a particular engine/method later.  If we only allow things which are compatible with everything, we'll likely not have much room for expression :)

**Comment by richardjgowers** [comment]
I think there is a question of if `AutoBox()` is a class which resolves later, or if resolves early (as in the classmethod I originally imagined).

**Comment by richardjgowers** [comment]
We're leaving this up to protocols in the end
