### ISSUE TITLE
gather should support simulation repeats submitted in parallel

### ISSUE THREAD

**Issue by atravitz** [OpenFreeEnergy/openfe#987]
When running quickrun in parallel, the directory structure changes so to be `results_0/`, `results_1/`, `results_2/` , and gather no longer works

We need to decide if gather should support this scenario, or if we need to be more strict about user-behavior.

**Comment by CurtisColwell** [comment]
Glad this is already here. I am running into this problem now. I changed the protocol_repeats to 1 to run each repeat separately, but it doesn't add to the currently existing .json output. Can I add the new 'protocol_result' and 'unit_results' or will this not work?

I nice solution would be adding the new repeat to the old output file instead of throwing this error:

**Error: Invalid value for '-o': File 'results/easy_rbfe_mol1_solvent_mol2_solvent.json' already exists.**
